redis = (loadfile "redis.lua")()
io.write("Enter aelegram ID : ")
local last = io.read()
io.write("\nEnter Full Sudo ID : ")
local sudo=io.read()
local text,ok = io.open("base.lua",'r'):read('*a'):gsub("aelegram%-ID",last)
io.open("aelegram-"..last..".lua",'w'):write(text):close()
io.open("aelegram-"..last..".sh",'w'):write("while true; do\n./telegram-cli-1222 -p aelegram-"..last.." -s aelegram-"..last..".lua\ndone"):close()
io.popen("chmod 777 aelegram-"..last..".sh")
redis:set('aelegram:'..last..':fullsudo',sudo)
print("Done!\nNew aelegram Created...\nID : "..last.."\nFull Sudo : "..sudo.."\nRun : ./aelegram-"..last..".sh")
